minio.endpoint=http://127.0.0.1:9000
minio.access-key=nFpKQzMpRQlBn05PrjzT
minio.secret-key=Sac0vCSvF3gEuDHUqulAXfLltuaXu1OGl09ILdJO
minio.region=us-east-1
minio.bucket=
minio.object=hello.txt
minio.content=hello from reactive minio sdk
